# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: veen.xyz
email: vincent@veen.xyz
description: Freelance Product Developer that can help building your MVP, product strategy and code reviews
baseurl: /
url: https://veen.xyz

# Gems
gems:
  - jekyll-assets

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - run
sass:
  style: compressed
assets:
  digest: true
